INSERT INTO `user` (`iduser`, `name`, `email`, `password`, `type`, `remember_token`, `avatar`, `postcode`, `city`, `street`, `country`) VALUES ('1', 'rahman', 'admin@empire.com', '$2a$12$0pgNKzLvPLdgwahoXSlbReUKPDczv6Udi3yLZsZusfMZi52rbzqTC', 'admin', NULL, NULL, '0000', 'shah alam', 'usj', 'malaysia');
INSERT INTO `user` (`iduser`, `name`, `email`, `password`, `type`, `remember_token`, `avatar`, `postcode`, `city`, `street`, `country`) VALUES ('2', 'staff1', 'staff1@empire.com', '$2a$12$0pgNKzLvPLdgwahoXSlbReUKPDczv6Udi3yLZsZusfMZi52rbzqTC', 'staff', NULL, NULL, '0000', 'shah alam', 'usj', 'malaysia');
INSERT INTO `user` (`iduser`, `name`, `email`, `password`, `type`, `remember_token`, `avatar`, `postcode`, `city`, `street`, `country`) VALUES ('3', 'recruit1', 'recruit1@empire.com', '$2a$12$0pgNKzLvPLdgwahoXSlbReUKPDczv6Udi3yLZsZusfMZi52rbzqTC', 'recruit', NULL, NULL, '0000', 'shah alam', 'usj', 'malaysia');
INSERT INTO `user` (`iduser`, `name`, `email`, `password`, `type`, `remember_token`, `avatar`, `postcode`, `city`, `street`, `country`) VALUES ('4', 'trainer1', 'trainer1@empire.com', '$2a$12$0pgNKzLvPLdgwahoXSlbReUKPDczv6Udi3yLZsZusfMZi52rbzqTC', 'trainer', NULL, NULL, '0000', 'shah alam', 'usj', 'malaysia');
INSERT INTO `user` (`iduser`, `name`, `email`, `password`, `type`, `remember_token`, `avatar`, `postcode`, `city`, `street`, `country`) VALUES ('5', 'lecturer1', 'lecturer1@empire.com', '$2a$12$0pgNKzLvPLdgwahoXSlbReUKPDczv6Udi3yLZsZusfMZi52rbzqTC', 'lecturer', NULL, NULL, '0000', 'shah alam', 'usj', 'malaysia');
INSERT INTO `user` (`iduser`, `name`, `email`, `password`, `type`, `postcode`, `city`, `street`, `country`) VALUES ('6', 'student1', 'student@empire.com', '$12$0pgNKzLvPLdgwahoXSlbReUKPDczv6Udi3yLZsZusfMZi52rbzqTC', 'student', '0000', 'shah alam', 'usj', 'malaysia');

INSERT INTO `trainer` (`idtrainer`, `phone`, `date_joined`, `expertise`, `user_iduser`) VALUES ('1', '0000', '2017-09-09', 'customer service', '4');
INSERT INTO `training` (`idtraining`, `name`, `type`, `description`, `trainer_id`) VALUES ('1', 'phone conversation', 'customer service', 'how to perform a phone conversation', '1');
INSERT INTO `training_address` (`idtraining_address`, `postcode`, `city`, `street`, `country`, `training_id`) VALUES ('1', '0000', 'subang', 'usj 1', 'malaysia', '1');
INSERT INTO `student` (`idstudent`, `user_iduser`, `semester`, `phone`, `date_registered`) VALUES ('1', '6', '1', '0000', '2017-09-09');
INSERT INTO `class` (`idclass`, `code`, `building`, `level`) VALUES ('1', 'XB02', '13', '8');
INSERT INTO `empire_portal`.`student_attendance` (`idstudent_attendance`, `class_id`, `student_id`, `date_time`) VALUES ('1', '1', '1', '2017-09-09 14:00:00');
INSERT INTO `empire_portal`.`student_module` (`idstudent_module`, `date_enrolled`, `student_id`, `student_user_id`) VALUES ('1', '2017-09-09', '1', '6');
INSERT INTO `empire_portal`.`module` (`idmodule`, `class_id`, `code`, `semester`, `name`, `description`, `year`, `student_module_id`, `cost`) VALUES ('1', '1', 'dip 2080', '1', 'introduction to customer service', 'details about customer service', '2017-09-09', '1', '1250');
INSERT INTO `empire_portal`.`student_payment` (`idstudent_payment`, `student_id`, `module_id`, `date_time`, `payment_type`) VALUES ('1', '1', '1', '2017-09-09 12:00:00', 'cash');
INSERT INTO `empire_portal`.`branch` (`idbranch`, `name`, `postcode`, `city`, `street`, `country`) VALUES ('1', 'boulevard', '0000', 'kl', 'persiwaran 19', 'malaysia');
INSERT INTO `empire_portal`.`staff` (`idstaff`, `user_id`, `position`, `role`, `date_joined`, `branch_id`) VALUES ('1', '2', 'clerical', 'reception', '2017-09-09', '1');
INSERT INTO `empire_portal`.`interview` (`idinterview`, `staff_id`, `date_time`, `domain`, `postcode`, `city`, `street`, `country`) VALUES ('1', '1', '2017-09-09 12:00:00', 'customer service', '0000', 'kl', 'usj 1', 'malaysia');
INSERT INTO `empire_portal`.`user` (`iduser`, `name`, `email`, `password`, `type`, `postcode`, `city`, `street`, `country`) VALUES ('7', 'employee1', 'employee1@empire.com', '$12$0pgNKzLvPLdgwahoXSlbReUKPDczv6Udi3yLZsZusfMZi52rbzqTC', 'employee', '000', 'shah alam', 'usj', 'malaysia');
UPDATE `empire_portal`.`user` SET `email`='student1@empire.com' WHERE `iduser`='6';
INSERT INTO `empire_portal`.`employee` (`idemployee`, `user_id`, `company`, `position`) VALUES ('1', '3', 'd2j', 'developer');
INSERT INTO `empire_portal`.`recruit` (`idrecruit`, `interview_id`, `user_id`, `applied_for`, `date_applied`, `employee_id`) VALUES ('1', '1', '3', 'customer service', '2017-09-09', '1');
INSERT INTO `empire_portal`.`lecturer` (`idlecturer`, `phone`, `date_joined`, `user_id`, `postcode`, `city`, `street`, `country`) VALUES ('1', '000', '2017-09-09', '5', '000', 'subang ', 'usj', 'malaysia');
INSERT INTO `empire_portal`.`leave` (`staff_id`, `id_leave`, `start`, `end`, `reason`) VALUES ('1', '1', '2017-09-09', '2017-09-14', 'medical');
INSERT INTO `empire_portal`.`user` (`iduser`, `name`, `email`, `password`, `type`, `postcode`, `city`, `street`, `country`) VALUES ('8', 'employer1', 'employer1@empire.com', '$12$0pgNKzLvPLdgwahoXSlbReUKPDczv6Udi3yLZsZusfMZi52rbzqTC', 'employer', '000', 'shah alam', 'usj', 'malaysia');
INSERT INTO `empire_portal`.`employer` (`idemployer`, `user_id`, `company`, `position`, `date_joined`) VALUES ('1', '8', 'd2j', 'manager', '2017-09-09');
INSERT INTO `empire_portal`.`enquiry` (`idenquiry`, `staff_id`, `date_time`, `description`) VALUES ('1', '1', '2017-09-09 12:00:00', 'How to apply to singapore?');
INSERT INTO `empire_portal`.`employment_history` (`idemployment_history`, `status`, `employer_id`, `employee_id`, `date_joined`) VALUES ('1', 'active', '1', '1', '2017-09-09');
INSERT INTO `empire_portal`.`employer_report` (`idemployee_report`, `employer_id`, `description`, `date`) VALUES ('1', '1', 'Report on the status of new requirements', '2017-09-09');
INSERT INTO `empire_portal`.`employer_notification` (`idnotification`, `employer_id`, `description`, `date_time`) VALUES ('1', '1', 'Urgently needed training for new employee', '2017-09-09');
